name:                asset-bundle
version:             0.1.0.0
github:              "deech/asset-bundle"
license:             BSD3
author:              "Aditya Siram"
maintainer:          "aditya.siram@gmail.com"
copyright:           "2018 Aditya Siram"
category:            distribution, bundle, zip, library, program
synopsis:            A build-time Cabal library that bundles executables with assets
extra-source-files:
- README.org

description:         Please see the Hackage documentation at <http://hackage.haskell.org/package/asset-bundle/docs/Distribution-Simple-AssetBundle.html>

dependencies:
- base >= 4.7 && < 5
- Cabal >= 1.24.0.0
- directory >= 1.2.4.0
- filepath
library:
  source-dirs: src
